# Generated by Django 5.0.7 on 2024-08-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_polluser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
